#%RAML 1.0
title: some-system-sapi
description: "API Catalog CLI De Publish Shite Mita"

types:
  dataType:
    type: !include data-types/dataType.raml

/some-resources:
  /actionOne:
    post:
      body:
        application/json:
          type: dataType
  /actionTwo:
    post:
      body:
        application/json:
          type: dataType
  /actionThree:
    post:
      body:
        application/json:
          type: dataType
  /actionFour:
    post:
      body:
        application/json:
          type: dataType
  /actionFive:
    post:
      body:
        application/json:
          type: dataType
  /actionSix:
    post:
      body:
        application/json:
          type: dataType
  /actionSeven:
    post:
      body:
        application/json:
          type: dataType
  /actionEight:
    post:
      body:
        application/json:
          type: dataType  
  /actionNine:
    post:
      body:
        application/json:
          type: dataType