#%RAML 1.0 DataType


type: object
properties:
  fieldOne:
    type: string
    example: 'One'
  fieldTwo:
    type: string
    example: 'Two'
  fieldThree:
    type: string
    example: 'Three'
  fieldFour:
    type: string
    example: 'Four'
  fieldFive:
    type: string
    example: 'Five'
  fieldSix:
    type: string
    example: 'Six'
  fieldSeven:
    type: string
    example: 'Seven'
  fieldEight:
    type: string
    example: 'Eight'