#%RAML 1.0 DataType


type: object
properties:
  field_one:
    type: string
    example: 'One'
  field_two:
    type: string
    example: 'Two'
  field_three:
    type: string
    example: 'Three'
  field_four:
    type: string
    example: 'Four'
  field_five:
    type: string
    example: 'Five'
  field_six:
    type: string
    example: 'Six'
  field_seven:
    type: string
    example: 'Seven'
  field_eight:
    type: string
    example: 'Eight'